config/routes.rb
Rails.application.routes.draw do
  post_to = ->path{post path, to: path.gsub("/", "#")}
  devise_for :mrs, only: []
  devise_for :doctor, only: []
  namespace :doctors, defaults: {format: :json} do
    resources :comments,        only: [:show, :create], controller: :comments
    resource  :confirm_email, only: [:create],          controller: :registrations
    resource  :check_uuid,    only: [:show],            controller: :registrations
    resource  :register,      only: [:update],          controller: :registrations
    resource  :login,         only: [:create],          controller: :sessions
    resource  :reset_request, only: [:reset_request],   controller: :sessions
    post "/reset_request"  => "sessions#reset_request"
    post "/reset"          => "sessions#reset"
    resources :posts,         only: [:new, :create, :destroy], controller: :posts
    resources :users,         only: [:index],           controller: :users
    resource  :users,         only: [:update],          controller: :users
    post "/resign_doctor" => "doctors#resign"
    post "/wrong_doctor" => "doctors#wrong"
    post "/license_check" => "doctors#license_check"
    resources :doctors,       only: [:index, :show, :update], controller: :doctors
    resources :images,        only: [:create],          controller: :images
    resource  :images,        only: [:destroy],         controller: :images
    resources :areas,         only: [:index, :show],    controller: :areas
    resources :prefectures,   only: [:index],           controller: :prefectures
    resources :icd10s,        only: [:index],           controller: :icd10s
    resources :hospitals,     only: [:index, :show],    controller: :hospitals
    resources :departments,   only: [:index, :show],    controller: :departments
    resources :societies,     only: [:index, :show],    controller: :societies
    resources :universities,  only: [:index],           controller: :universities
    resources :recommends,    only: [:create, :destroy], controller: :recommends
    resources :shines,        only: [:show, :create], controller: :shines
    resources :links,         only: [:index, :create, :show], controller: :links
    resource  :links,         only: [:update],          controller: :links
    resource  :links,         only: [:destroy],         controller: :links
    resources :invitees,      only: [:index],           controller: :temporary_doctors
    resources :skills,        only: [:index, :show],    controller: :skills
    resources :timelines,     only: [:index, :destroy], controller: :timelines
    resources :uploaded_files, only: [:create, :destroy], controller: :uploaded_files
    resources :monographs, only: [:create, :update], controller: :monographs
    resources :pre_monographs, only: [:show], controller: :pre_monographs
    resources :whytlink_messages, only: [:index, :create]
    resources :whytlink_doctor_chatrooms, only: :destroy
    resources :emergency_doctor_hospitals, only: [:index, :create]
    resources :doctor_feedbacks, only: [:index, :update]
    resources :emergency_requests, only: [:create, :show, :update]
    resources :whytlink_chatrooms, only: [:index, :show, :create, :update]
    resources :favorite_groups, only: [:index, :show, :create, :update]
    resources :specialties, only: :index
    resources :doctor_specialties, only: :create
    resources :whytlink_group_chat_requests, only: [:create, :update]
    resources :emergency_doctors, only: :update
    resources :emergency_request_hospitals, only: :update
    get  "/invitees/test:id"   => "invitees#test"
    get  "/doctors/test/:id"   => "doctors#test"
    get  "/skills/test/"       => "skills#test"
    get  "/pre_monographs/status/:doctor_id" => "pre_monographs#status"
    get  "/pre_monographs/scrape/:doctor_id" => "pre_monographs#scrape"
    post "/pre_monographs/scrape_html/:doctor_id" => "pre_monographs#scrape_html"
    put  "/pre_monographs/confirm/:id" => "pre_monographs#confirm"
    post "/doctors/search" => "doctors#custom_search"
    post "/shines_del" => "shines#del"
    post "/comments_del" => "comments#del"
  end

  namespace :mrs, defaults: {format: :json} do
    resources :whytplot_messages, only: [:index]
    resources :whytplot_chatrooms, only: [:index, :create, :update, :show]
    resources :whytplot_mr_chatrooms, only: [:update]
  end

  %w(
    mr_sessions/create mr_sessions/destroy
    mrs/update
  ).each &post_to

  resources :mrs, only: [:index, :show, :create, :edit]
  resources :projects, only: [:index, :create, :update, :show]
  resources :branches, only: [:index, :create, :update, :show]
  resources :companies, only: [:show]
  resources :charts, only: [:index, :create, :update, :show]
  resources :scenarios, only: [:index, :create, :update, :show]
  resources :dr_mr_chatrooms, only: [:index, :create, :update, :show]
  resources :dr_mr_messages, only: [:index, :create]

  scope :admin do
    resources :all_mails
    resources :mail_logs
    resources :chart_types
    resources :whytplot_export_errors, :only => [:index, :destroy]
    get   '/datafiles/'          => 'datafiles#index'
    get   '/datafiles/:year'     => 'datafiles#list'
    get   '/datafiles/:year/:id' => 'datafiles#show'
    post  '/datafiles/import'    => 'datafiles#import'
  end

  scope :whyt_plot do
    get '/api/:api_name', :to=> "whyt_plots#index"
  end

  resources :whyt_plot_apis
  resources :whyt_plot_table_views do
    collection do
      get  'download'
      get  'timestamp_latest' => 'whyt_plot_table_views#latest'
      post 'export'
      post 'drop_view'
    end
  end

  resources :society_positions
  resources :staff_logs

  resources :departments
  devise_for :users, controllers: {
    sessions: "users/sessions"
  }

  get    "/leader"       => "leaders#home",   as: "home_leader"
  patch  "/leader"       => "leaders#update", as: "update_leader"
  patch  "/leader/batch" => "leaders#batch",  as: "batch_leader"

  resources :staffs
  resources :sheets
  resources :doctors

  scope :work do
    resources :duplicate_doctor_lists do
      member do
        patch "merge"
      end
    end
    resources :universities do
      collection do
        patch "merge"
      end
    end
    resources :societies do
      collection do
        patch "merge"
      end
    end
    resources :hospitals do
      collection do
        patch "merge"
      end
    end
    resources :duplicate_hospitals do
      collection do
        patch "merge"
      end
    end
    resources :staff_posts
  end

  root "tops#index"
  get "/strong_logout" => "tops#logout"
  get "/kanri" => "tops#index"
  get "/database_work" => "works#top"
  get "/department_official_category" => "works#department_list_json"
  get "/department_position_names" => "works#department_position_names"
  get "/work_prefecture_select/:id" => "works#prefecture_select"
  get "/work_department_select/:id" => "works#department_select"
  get "/work_department/:id" => "works#department"
  patch "/work_department/:id/list" => "works#update_department_lists", as: "update_work_department_lists"

  get "/plural_doctors_all" => "doctors#plural_doctors_all"
  get "/plural_doctors/:id" => "doctors#plural_doctors"
  get "/typeaheads/university" => "typeaheads#university"
  get "/typeaheads/society" => "typeaheads#society"
  get "/typeaheads/society_position/:society_id" => "typeaheads#society_position"

  resources :specialties, only: :index

end

app/models/datafile.rb
class Datafile < ActiveRecord::Base
  after_initialize :set_default_value, if: :new_record?
  enum status: { not_yet_import: 0, importing: 1, imported: 2, cannot_imoprt: 3, failed: 4}

  private
  def set_default_value
    if filepath =~ /.xls|.xlsx|.csv|.CSV/
      self.status = :not_yet_import
    else
      self.status = :cannot_imoprt
    end
  end

end

app/controllers/datafiles_controller.rb
require 'aws-sdk-resources'

class DatafilesController < ApplicationController
  layout "work_layout"
  before_action :redirect_root_if_not_login
  # before_action :set_duplicate_docter_list, only: [:show, :update, :merge]

  respond_to :html

  def index
    wp_bucket = Aws::S3::Resource.new(region: 'ap-northeast-1').bucket('rw-rails-data')
    @s3_folder = wp_bucket.objects.map { |obj|
      obj.key =~ /^whytplot-data\/([0-9]{4,})\/$/ ? obj : nil;
    }.compact

    @years = @s3_folder.map do |dir|
      if dir.key =~ /[0-9]{4,}/ then $& end
    end
  end

  def show
    @year = params[:year]
    @datafile = Datafile.find(params[:id])
  end

  def list
    wp_bucket = Aws::S3::Resource.new(region: 'ap-northeast-1').bucket('rw-rails-data')
    @datafiles = Array.new
    wp_bucket.objects(prefix: "whytplot-data/#{params[:year]}/").each do |obj|
      if obj.key =~ /^whytplot-data\/([0-9]{4})\/.+/ && File.extname(obj.key).present?
        @datafiles.push(Datafile.find_or_initialize_by(filepath: "#{obj.key}"))
      end
    end
  end

  def edit
  end

  def new
  end

  def create
  end

  def update
  end

  def destroy
  end

  def import
    import_params = params[:import]

    if import_params.nil?
      redirect_to datafiles_path, alert: "パラメータが不正です", status: 505
      return
    end

    import_params.each do | key, item |
      #チェックがついているものだけ実行
      if item[:do]
        s3_filepath  = item[:filepath]
        file_name = s3_filepath =~ /^whytplot-data\/([0-9]{4,}|.+)\// ? $' : nil

        # s3のファイル一旦public/にダウンロードする
        s3 = Aws::S3::Client.new(region: 'ap-northeast-1')
        File.open("#{Rails.root}/tmp/datafiles/#{file_name}", "wb") do |file|
          s3.get_object(bucket: 'rw-rails-data', key: "#{s3_filepath}") do |chunk|
            file.write chunk
          end
        end

        year = s3_filepath =~ /\/[0-9]{4,}\// ? $&.delete("/") : nil
        filepath = "#{Rails.root}/tmp/datafiles/#{file_name}"
        datafile = Datafile.find_or_initialize_by(filepath: s3_filepath)
        datafile.status = :importing
        datafile.filepath = s3_filepath
        datafile.save!

        # TODO 本番ではコメントアウト必要
        ImportJob.perform_later(filepath, s3_filepath, year)
        # ImportJob.new.perform(filepath, s3_filepath, year)
      end
    end
    redirect_to :back, notice: "インポートを実行しました"
  end
end

app/views/datafiles/index.html.slim
.row
  .col-lg-12
    h4 インポート一覧
    div[style="margin-bottom: 20px"]
      = link_to 'API一覧', whyt_plot_apis_path
      = link_to 'ビュー一覧', whyt_plot_table_views_path, :style => " margin-left: 10px"
      = link_to 'エクスポートエラ一覧', whytplot_export_errors_path, :style => " margin-left: 10px"
    blockquote
      p 年度別
    - if @s3_folder.present?
      ul.list-group
        - @s3_folder.each_with_index do |directory, i|
          li.list-group-item
            p.h5 = link_to directory.key, { :controller => :datafiles, :action => :list, :year => @years[i]}
    - else
      - p flash[:notice]
    blockquote
      p データ情報
    table.table.table-bordered.table-striped.datafiles
      thead
        tr
          th テーブル名
          th データ数
      tbody
        tr
          td mdc_layer1_codes
          td.text-right #{MdcLayer1Code.all.count}
        tr
          td mdc_layer1s
          td.text-right #{MdcLayer1.all.count}
        tr
          td mdc_layer2s
          td.text-right #{MdcLayer2.all.count}
        tr
          td mdc_layer3s
          td.text-right #{MdcLayer3.all.count}
        tr
          td kcodes
          td.text-right #{Kcode.all.count}
        tr
          td medical_regions
          td.text-right #{MedicalRegion.all.count}
        tr
          td medical_municipalities
          td.text-right #{MedicalMunicipality.all.count}
        tr
          td addresses
          td.text-right #{Address.all.count}
        tr
          td municipalities
          td.text-right #{Municipality.all.count}
        tr
          td populations
          td.text-right #{Population.all.count}
        tr
          td dpc_hospitals
          td.text-right #{DpcHospital.all.count}
        tr
          td ag_by_dpch_x_mdc_l1cs
          td.text-right #{AgByDpchXMdcL1c.all.count}
        tr
          td ag_by_dpch_x_mdc_l2s
          td.text-right #{AgByDpchXMdcL2.all.count}
        tr
          td ag_by_dpch_x_reason_majors
          td.text-right #{AgByDpchXReasonMajor.all.count}
        tr
          td ag_by_dpch_x_reason_minors
          td.text-right #{AgByDpchXReasonMinor.all.count}
        tr
          td ag_by_dpch_x_mdc_l2_treatments
          td.text-right #{AgByDpchXMdcL2Treatment.all.count}
        tr
          td ag_by_mdc_l1s
          td.text-right #{AgByMdcL1.all.count}
        tr
          td regimen_pharmacy_rankings
          td.text-right #{RegimenPharmacyRanking.all.count}
        tr
          td regimen_regimen_rankings
          td.text-right #{RegimenRegimenRanking.all.count}
        tr
          td ag_by_mdcs
          td.text-right #{AgByMdc.all.count}
        tr
          td number_by_codes
          td.text-right #{NumberByCode.all.count}
  .col-lg-12
    div[style="margin-bottom: 20px"]
      = link_to 'API一覧', whyt_plot_apis_path
      = link_to 'ビュー一覧', whyt_plot_table_views_path, :style => " margin-left: 10px"
      = link_to 'エクスポートエラ一覧', whytplot_export_errors_path, :style => " margin-left: 10px"

app/views/datafiles/list.html.slim
.row
  .col-lg-12
    h4 Excelファイル読み込み
    div[style="margin-bottom: 20px"]
      = link_to '年度別一覧に戻る', datafiles_path
      = link_to 'API一覧', whyt_plot_apis_path, :style => " margin-left: 10px"
      = link_to 'インポート一覧', datafiles_path, :style => " margin-left: 10px"
    = form_tag({ :controller => :datafiles, :action => :import }, { :method => :post }) do
      =submit_tag "インポート", :class => "btn btn-primary btn-large", :style => "margin-bottom: 10px"
      table.table.table-bordered.table-striped.datafiles
        thead
          tr
            th 選択
            th ファイルid
            th URL
            th インポート
            th データ行数
            th エラー数
            th ワーニング数
        tbody
          - @datafiles.each_with_index do |datafile, index|
            = hidden_field_tag  "import[" + index.to_s + "][id]",  datafile.id
            = hidden_field_tag  "import[" + index.to_s + "][filepath]", datafile.filepath
            tr
              td
                - if datafile.status == 'cannot_imoprt'
                  = check_box_tag "import[" + index.to_s + "][do]", true, false, {disabled:true}
                - else
                  = check_box_tag "import[" + index.to_s + "][do]", true, false
              td = datafile.id
              td
                = link_to_if datafile.id.present?, datafile.filepath,
                { :controller => :datafiles, :action => :show, :id => datafile.id }
              td
                div.status[class="#{datafile.status}"] = datafile.status_i18n
              td = datafile.total_line_num
              td = datafile.error_line_num
              td = datafile.warning_line_num
      =submit_tag "インポート", :class => "btn btn-primary btn-large"

app/views/datafiles/show.html.slim
.container
  .row
    .col-lg-12
      h4 =@datafile.filepath
      =link_to "一覧へ戻る", { :controller => :datafiles, :action => :list, :year => @year }
.container.show-datafile
  .row
    .col-lg-6.col-md-6.col-sm-6
      dl
        dt インポート日
        dd=@datafile.updated_at
    .col-lg-6.col-md-6.col-sm-6
      dl
        dt ステータス
        dd[style="font-size: 26px"]=@datafile.status_i18n
  .row
    .col-lg-4.col-md-4.col-sm-4
      dl
        dt 読み込みデータ行数
        dd=@datafile.total_line_num
    .col-lg-4.col-md-4.col-sm-4
      dl
        dt エラー数
        dd =@datafile.error_line_num
    .col-lg-4.col-md-4.col-sm-4
      dl
        dt ワーニング数
        dd =@datafile.warning_line_num
.container.show-datafile-messages
  .row
    .col-lg-12
      dl
        dt エラーログ
        dd =simple_format @datafile.messages
      =link_to "一覧へ戻る", { :controller => :datafiles, :action => :list, :year => @year }