config/routes.rb
Rails.application.routes.draw do
  post_to = ->path{post path, to: path.gsub("/", "#")}
  devise_for :mrs, only: []
  devise_for :doctor, only: []
  namespace :doctors, defaults: {format: :json} do
    resources :comments,        only: [:show, :create], controller: :comments
    resource  :confirm_email, only: [:create],          controller: :registrations
    resource  :check_uuid,    only: [:show],            controller: :registrations
    resource  :register,      only: [:update],          controller: :registrations
    resource  :login,         only: [:create],          controller: :sessions
    resource  :reset_request, only: [:reset_request],   controller: :sessions
    post "/reset_request"  => "sessions#reset_request"
    post "/reset"          => "sessions#reset"
    resources :posts,         only: [:new, :create, :destroy], controller: :posts
    resources :users,         only: [:index],           controller: :users
    resource  :users,         only: [:update],          controller: :users
    post "/resign_doctor" => "doctors#resign"
    post "/wrong_doctor" => "doctors#wrong"
    post "/license_check" => "doctors#license_check"
    resources :doctors,       only: [:index, :show, :update], controller: :doctors
    resources :images,        only: [:create],          controller: :images
    resource  :images,        only: [:destroy],         controller: :images
    resources :areas,         only: [:index, :show],    controller: :areas
    resources :prefectures,   only: [:index],           controller: :prefectures
    resources :icd10s,        only: [:index],           controller: :icd10s
    resources :hospitals,     only: [:index, :show],    controller: :hospitals
    resources :departments,   only: [:index, :show],    controller: :departments
    resources :societies,     only: [:index, :show],    controller: :societies
    resources :universities,  only: [:index],           controller: :universities
    resources :recommends,    only: [:create, :destroy], controller: :recommends
    resources :shines,        only: [:show, :create], controller: :shines
    resources :links,         only: [:index, :create, :show], controller: :links
    resource  :links,         only: [:update],          controller: :links
    resource  :links,         only: [:destroy],         controller: :links
    resources :invitees,      only: [:index],           controller: :temporary_doctors
    resources :skills,        only: [:index, :show],    controller: :skills
    resources :timelines,     only: [:index, :destroy], controller: :timelines
    resources :uploaded_files, only: [:create, :destroy], controller: :uploaded_files
    resources :monographs, only: [:create, :update], controller: :monographs
    resources :pre_monographs, only: [:show], controller: :pre_monographs
    resources :whytlink_messages, only: [:index, :create]
    resources :whytlink_doctor_chatrooms, only: :destroy
    resources :emergency_doctor_hospitals, only: [:index, :create]
    resources :doctor_feedbacks, only: [:index, :update]
    resources :emergency_requests, only: [:create, :show, :update]
    resources :whytlink_chatrooms, only: [:index, :show, :create, :update]
    resources :favorite_groups, only: [:index, :show, :create, :update]
    resources :specialties, only: :index
    resources :doctor_specialties, only: :create
    resources :whytlink_group_chat_requests, only: [:create, :update]
    resources :emergency_doctors, only: :update
    resources :emergency_request_hospitals, only: :update
    get  "/invitees/test:id"   => "invitees#test"
    get  "/doctors/test/:id"   => "doctors#test"
    get  "/skills/test/"       => "skills#test"
    get  "/pre_monographs/status/:doctor_id" => "pre_monographs#status"
    get  "/pre_monographs/scrape/:doctor_id" => "pre_monographs#scrape"
    post "/pre_monographs/scrape_html/:doctor_id" => "pre_monographs#scrape_html"
    put  "/pre_monographs/confirm/:id" => "pre_monographs#confirm"
    post "/doctors/search" => "doctors#custom_search"
    post "/shines_del" => "shines#del"
    post "/comments_del" => "comments#del"
  end

  namespace :mrs, defaults: {format: :json} do
    resources :whytplot_messages, only: [:index]
    resources :whytplot_chatrooms, only: [:index, :create, :update, :show]
    resources :whytplot_mr_chatrooms, only: [:update]
  end

  %w(
    mr_sessions/create mr_sessions/destroy
    mrs/update
  ).each &post_to

  resources :mrs, only: [:index, :show, :create, :edit]
  resources :projects, only: [:index, :create, :update, :show]
  resources :branches, only: [:index, :create, :update, :show]
  resources :companies, only: [:show]
  resources :charts, only: [:index, :create, :update, :show]
  resources :scenarios, only: [:index, :create, :update, :show]
  resources :dr_mr_chatrooms, only: [:index, :create, :update, :show]
  resources :dr_mr_messages, only: [:index, :create]

  scope :admin do
    resources :all_mails
    resources :mail_logs
    resources :chart_types
    resources :whytplot_export_errors, :only => [:index, :destroy]
    get   '/datafiles/'          => 'datafiles#index'
    get   '/datafiles/:year'     => 'datafiles#list'
    get   '/datafiles/:year/:id' => 'datafiles#show'
    post  '/datafiles/import'    => 'datafiles#import'
  end

  scope :whyt_plot do
    get '/api/:api_name', :to=> "whyt_plots#index"
  end

  resources :whyt_plot_apis
  resources :whyt_plot_table_views do
    collection do
      get  'download'
      get  'timestamp_latest' => 'whyt_plot_table_views#latest'
      post 'export'
      post 'drop_view'
    end
  end

  resources :society_positions
  resources :staff_logs

  resources :departments
  devise_for :users, controllers: {
    sessions: "users/sessions"
  }

  get    "/leader"       => "leaders#home",   as: "home_leader"
  patch  "/leader"       => "leaders#update", as: "update_leader"
  patch  "/leader/batch" => "leaders#batch",  as: "batch_leader"

  resources :staffs
  resources :sheets
  resources :doctors

  scope :work do
    resources :duplicate_doctor_lists do
      member do
        patch "merge"
      end
    end
    resources :universities do
      collection do
        patch "merge"
      end
    end
    resources :societies do
      collection do
        patch "merge"
      end
    end
    resources :hospitals do
      collection do
        patch "merge"
      end
    end
    resources :duplicate_hospitals do
      collection do
        patch "merge"
      end
    end
    resources :staff_posts
  end

  root "tops#index"
  get "/strong_logout" => "tops#logout"
  get "/kanri" => "tops#index"
  get "/database_work" => "works#top"
  get "/department_official_category" => "works#department_list_json"
  get "/department_position_names" => "works#department_position_names"
  get "/work_prefecture_select/:id" => "works#prefecture_select"
  get "/work_department_select/:id" => "works#department_select"
  get "/work_department/:id" => "works#department"
  patch "/work_department/:id/list" => "works#update_department_lists", as: "update_work_department_lists"

  get "/plural_doctors_all" => "doctors#plural_doctors_all"
  get "/plural_doctors/:id" => "doctors#plural_doctors"
  get "/typeaheads/university" => "typeaheads#university"
  get "/typeaheads/society" => "typeaheads#society"
  get "/typeaheads/society_position/:society_id" => "typeaheads#society_position"

  resources :specialties, only: :index

end

app/models/sheet.rb
class Sheet < ActiveRecord::Base
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  before_action :redirect_root_if_not_login  
  before_action :set_sheet, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @sheets = Sheet.all
    respond_with(@sheets)
  end

  def show
    respond_with(@sheet)
  end

  def new
    @sheet = Sheet.new
    respond_with(@sheet)
  end

  def edit
  end

  def create
    @sheet = Sheet.new(sheet_params)
    @sheet.save
    respond_with(@sheet)
  end

  def update
    @sheet.update(sheet_params)
    respond_with(@sheet)
  end

  def destroy
    @sheet.destroy
    respond_with(@sheet)
  end

  private
    def set_sheet
      @sheet = Sheet.find(params[:id])
    end

    def sheet_params
      params.require(:sheet).permit(:area, :medical_group, :work_status, :hospital_id, :hospital_name, :doctor_name, :position, :department, :university, :graduation_year, :society, :profession, :skill, :result, :link, :history, :top_or_next, :user, :created_at, :updated_at, :update_user, :comment)
    end
end

app/helpers/sheets_helper.rb
module SheetsHelper
end

app/views/sheets/_form.html.slim
= form_for @sheet do |f|
  - if @sheet.errors.any?
    #error_explanation
      h2 = "#{pluralize(@sheet.errors.count, "error")} prohibited this sheet from being saved:"
      ul
        - @sheet.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :area
    = f.text_field :area
  .field
    = f.label :medical_group
    = f.text_field :medical_group
  .field
    = f.label :work_status
    = f.text_field :work_status
  .field
    = f.label :hospital_id
    = f.text_field :hospital_id
  .field
    = f.label :hospital_name
    = f.text_field :hospital_name
  .field
    = f.label :doctor_name
    = f.text_field :doctor_name
  .field
    = f.label :position
    = f.text_field :position
  .field
    = f.label :department
    = f.text_field :department
  .field
    = f.label :university
    = f.text_field :university
  .field
    = f.label :graduation_year
    = f.text_field :graduation_year
  .field
    = f.label :society
    = f.text_area :society
  .field
    = f.label :profession
    = f.text_field :profession
  .field
    = f.label :skill
    = f.text_area :skill
  .field
    = f.label :result
    = f.text_area :result
  .field
    = f.label :link
    = f.text_area :link
  .field
    = f.label :history
    = f.text_area :history
  .field
    = f.label :top_or_next
    = f.text_field :top_or_next
  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :created_at
    = f.text_field :created_at
  .field
    = f.label :updated_at
    = f.text_field :updated_at
  .field
    = f.label :update_user
    = f.text_field :update_user
  .field
    = f.label :comment
    = f.text_area :comment
  .actions = f.submit

app/views/sheets/edit.html.slim
h1 Editing sheet

== render 'form'

= link_to 'Show', @sheet
'|
= link_to 'Back', sheets_path

app/views/sheets/index.html.slim
h1 Listing sheets

table
  thead
    tr
      th Area
      th Medical group
      th Work status
      th Hospital
      th Hospital name
      th Doctor name
      th Position
      th Department
      th University
      th Graduation year
      th Society
      th Profession
      th Skill
      th Result
      th Link
      th History
      th Top or next
      th User
      th Created at
      th Updated at
      th Update user
      th Comment
      th
      th
      th

  tbody
    - @sheets.each do |sheet|
      tr
        td = sheet.area
        td = sheet.medical_group
        td = sheet.work_status
        td = sheet.hospital_id
        td = sheet.hospital_name
        td = sheet.doctor_name
        td = sheet.position
        td = sheet.department
        td = sheet.university
        td = sheet.graduation_year
        td = sheet.society
        td = sheet.profession
        td = sheet.skill
        td = sheet.result
        td = sheet.link
        td = sheet.history
        td = sheet.top_or_next
        td = sheet.user
        td = sheet.created_at
        td = sheet.updated_at
        td = sheet.update_user
        td = sheet.comment
        td = link_to 'Show', sheet
        td = link_to 'Edit', edit_sheet_path(sheet)
        td = link_to 'Destroy', sheet, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Sheet', new_sheet_path

app/views/sheets/new.html.slim
h1 New sheet

== render 'form'

= link_to 'Back', sheets_path

app/views/sheets/show.html.slim
p#notice = notice

p
  strong Area:
  = @sheet.area
p
  strong Medical group:
  = @sheet.medical_group
p
  strong Work status:
  = @sheet.work_status
p
  strong Hospital:
  = @sheet.hospital_id
p
  strong Hospital name:
  = @sheet.hospital_name
p
  strong Doctor name:
  = @sheet.doctor_name
p
  strong Position:
  = @sheet.position
p
  strong Department:
  = @sheet.department
p
  strong University:
  = @sheet.university
p
  strong Graduation year:
  = @sheet.graduation_year
p
  strong Society:
  = @sheet.society
p
  strong Profession:
  = @sheet.profession
p
  strong Skill:
  = @sheet.skill
p
  strong Result:
  = @sheet.result
p
  strong Link:
  = @sheet.link
p
  strong History:
  = @sheet.history
p
  strong Top or next:
  = @sheet.top_or_next
p
  strong User:
  = @sheet.user
p
  strong Created at:
  = @sheet.created_at
p
  strong Updated at:
  = @sheet.updated_at
p
  strong Update user:
  = @sheet.update_user
p
  strong Comment:
  = @sheet.comment

= link_to 'Edit', edit_sheet_path(@sheet)
'|
= link_to 'Back', sheets_path