config/routes.rb
Rails.application.routes.draw do
  post_to = ->path{post path, to: path.gsub("/", "#")}
  devise_for :mrs, only: []
  devise_for :doctor, only: []
  namespace :doctors, defaults: {format: :json} do
    resources :comments,        only: [:show, :create], controller: :comments
    resource  :confirm_email, only: [:create],          controller: :registrations
    resource  :check_uuid,    only: [:show],            controller: :registrations
    resource  :register,      only: [:update],          controller: :registrations
    resource  :login,         only: [:create],          controller: :sessions
    resource  :reset_request, only: [:reset_request],   controller: :sessions
    post "/reset_request"  => "sessions#reset_request"
    post "/reset"          => "sessions#reset"
    resources :posts,         only: [:new, :create, :destroy], controller: :posts
    resources :users,         only: [:index],           controller: :users
    resource  :users,         only: [:update],          controller: :users
    post "/resign_doctor" => "doctors#resign"
    post "/wrong_doctor" => "doctors#wrong"
    post "/license_check" => "doctors#license_check"
    resources :doctors,       only: [:index, :show, :update], controller: :doctors
    resources :images,        only: [:create],          controller: :images
    resource  :images,        only: [:destroy],         controller: :images
    resources :areas,         only: [:index, :show],    controller: :areas
    resources :prefectures,   only: [:index],           controller: :prefectures
    resources :icd10s,        only: [:index],           controller: :icd10s
    resources :hospitals,     only: [:index, :show],    controller: :hospitals
    resources :departments,   only: [:index, :show],    controller: :departments
    resources :societies,     only: [:index, :show],    controller: :societies
    resources :universities,  only: [:index],           controller: :universities
    resources :recommends,    only: [:create, :destroy], controller: :recommends
    resources :shines,        only: [:show, :create], controller: :shines
    resources :links,         only: [:index, :create, :show], controller: :links
    resource  :links,         only: [:update],          controller: :links
    resource  :links,         only: [:destroy],         controller: :links
    resources :invitees,      only: [:index],           controller: :temporary_doctors
    resources :skills,        only: [:index, :show],    controller: :skills
    resources :timelines,     only: [:index, :destroy], controller: :timelines
    resources :uploaded_files, only: [:create, :destroy], controller: :uploaded_files
    resources :monographs, only: [:create, :update], controller: :monographs
    resources :pre_monographs, only: [:show], controller: :pre_monographs
    resources :whytlink_messages, only: [:index, :create]
    resources :whytlink_doctor_chatrooms, only: :destroy
    resources :emergency_doctor_hospitals, only: [:index, :create]
    resources :doctor_feedbacks, only: [:index, :update]
    resources :emergency_requests, only: [:create, :show, :update]
    resources :whytlink_chatrooms, only: [:index, :show, :create, :update]
    resources :favorite_groups, only: [:index, :show, :create, :update]
    resources :specialties, only: :index
    resources :doctor_specialties, only: :create
    resources :whytlink_group_chat_requests, only: [:create, :update]
    resources :emergency_doctors, only: :update
    resources :emergency_request_hospitals, only: :update
    get  "/invitees/test:id"   => "invitees#test"
    get  "/doctors/test/:id"   => "doctors#test"
    get  "/skills/test/"       => "skills#test"
    get  "/pre_monographs/status/:doctor_id" => "pre_monographs#status"
    get  "/pre_monographs/scrape/:doctor_id" => "pre_monographs#scrape"
    post "/pre_monographs/scrape_html/:doctor_id" => "pre_monographs#scrape_html"
    put  "/pre_monographs/confirm/:id" => "pre_monographs#confirm"
    post "/doctors/search" => "doctors#custom_search"
    post "/shines_del" => "shines#del"
    post "/comments_del" => "comments#del"
  end

  namespace :mrs, defaults: {format: :json} do
    resources :whytplot_messages, only: [:index]
    resources :whytplot_chatrooms, only: [:index, :create, :update, :show]
    resources :whytplot_mr_chatrooms, only: [:update]
  end

  %w(
    mr_sessions/create mr_sessions/destroy
    mrs/update
  ).each &post_to

  resources :mrs, only: [:index, :show, :create, :edit]
  resources :projects, only: [:index, :create, :update, :show]
  resources :branches, only: [:index, :create, :update, :show]
  resources :companies, only: [:show]
  resources :charts, only: [:index, :create, :update, :show]
  resources :scenarios, only: [:index, :create, :update, :show]
  resources :dr_mr_chatrooms, only: [:index, :create, :update, :show]
  resources :dr_mr_messages, only: [:index, :create]

  scope :admin do
    resources :all_mails
    resources :mail_logs
    resources :chart_types
    resources :whytplot_export_errors, :only => [:index, :destroy]
    get   '/datafiles/'          => 'datafiles#index'
    get   '/datafiles/:year'     => 'datafiles#list'
    get   '/datafiles/:year/:id' => 'datafiles#show'
    post  '/datafiles/import'    => 'datafiles#import'
  end

  scope :whyt_plot do
    get '/api/:api_name', :to=> "whyt_plots#index"
  end

  resources :whyt_plot_apis
  resources :whyt_plot_table_views do
    collection do
      get  'download'
      get  'timestamp_latest' => 'whyt_plot_table_views#latest'
      post 'export'
      post 'drop_view'
    end
  end

  resources :society_positions
  resources :staff_logs

  resources :departments
  devise_for :users, controllers: {
    sessions: "users/sessions"
  }

  get    "/leader"       => "leaders#home",   as: "home_leader"
  patch  "/leader"       => "leaders#update", as: "update_leader"
  patch  "/leader/batch" => "leaders#batch",  as: "batch_leader"

  resources :staffs
  resources :sheets
  resources :doctors

  scope :work do
    resources :duplicate_doctor_lists do
      member do
        patch "merge"
      end
    end
    resources :universities do
      collection do
        patch "merge"
      end
    end
    resources :societies do
      collection do
        patch "merge"
      end
    end
    resources :hospitals do
      collection do
        patch "merge"
      end
    end
    resources :duplicate_hospitals do
      collection do
        patch "merge"
      end
    end
    resources :staff_posts
  end

  root "tops#index"
  get "/strong_logout" => "tops#logout"
  get "/kanri" => "tops#index"
  get "/database_work" => "works#top"
  get "/department_official_category" => "works#department_list_json"
  get "/department_position_names" => "works#department_position_names"
  get "/work_prefecture_select/:id" => "works#prefecture_select"
  get "/work_department_select/:id" => "works#department_select"
  get "/work_department/:id" => "works#department"
  patch "/work_department/:id/list" => "works#update_department_lists", as: "update_work_department_lists"

  get "/plural_doctors_all" => "doctors#plural_doctors_all"
  get "/plural_doctors/:id" => "doctors#plural_doctors"
  get "/typeaheads/university" => "typeaheads#university"
  get "/typeaheads/society" => "typeaheads#society"
  get "/typeaheads/society_position/:society_id" => "typeaheads#society_position"

  resources :specialties, only: :index

end

app/controllers/whyt_plot_table_views_controller.rb
# -*- coding: utf-8 -*-
class WhytPlotTableViewsController < ApplicationController
  layout "work_layout"
  before_action :set_whyt_plot_table_view

  def index
    @whyt_plot_table_views = WhytPlotTableView.all
    @sqlite_files = WhytPlotTableView.get_whytplot_sqlite_files
  end

  def new
    @whyt_plot_table_view = WhytPlotTableView.new
  end

  def create
    @whyt_plot_table_view = WhytPlotTableView.new(whyt_plot_table_view_params)
    if @whyt_plot_table_view.save
      redirect_to whyt_plot_table_views_path,
      flash: { notice: 'レコードが追加されました' } and return
    else
      redirect_to new_whyt_plot_table_view_path,
      flash: { errors: @whyt_plot_table_view.errors.full_messages } and return
    end
  end

  def show
    @whyt_plot_table_view
  end

  def edit
    @whyt_plot_table_view
  end

  def update
    @whyt_plot_table_view.update_attributes(whyt_plot_table_view_params)
    redirect_to edit_whyt_plot_table_view_path(@whyt_plot_table_view),
    flash: { errors: @whyt_plot_table_view.errors.full_messages }
  end

  def destroy
    whytplot_table_view = WhytPlotTableView.find(params[:id])
    @whyt_plot_table_view.destroy
    redirect_to whyt_plot_table_views_path
  end

  def export
    # TODO 本番ではコメントアウト必要
    WhytplotDbExportJob.perform_later(params[:is_production])
    # WhytplotDbExportJob.new.perform(params[:is_production])
    redirect_to whyt_plot_table_views_path
  end

  def download
    timestamp = params[:timestamp]
    user_id = params[:user_id]
    user = User.find_by_id(user_id)
    unless user.present? then
      render json: { message: 'user not found' }, :status => 404 and return
    end
    filename = WhytPlotTableView.get_whytplot_data(timestamp, user)
    filepath = Dir.glob("tmp/datafiles/#{filename}")
    unless filepath.present? then
      render json: { message: 'file not found'}, :status => 404 and return
    end

    stat = File::stat(filepath[0])
    if filepath.present?
      send_file(filepath[0], :filename => filename, :length => stat.size)
    end
  end

  def latest
    user_id = params[:user_id]
    user = User.find_by_id(user_id)
    result = WhytPlotTableView.get_latest_version(user)
    unless result.present?
      render json: { message: 'file not found' }, :status => 404
    else
      render json: { timestamp: result }
    end
  end

  private

    def set_whyt_plot_table_view
      @whyt_plot_table_view =
        params[:id] ? WhytPlotTableView.find(params[:id]) : nil
    end

    def whyt_plot_table_view_params
      params.require(:whyt_plot_table_view).permit(
        :name, :create_view_sql, :is_view, :description
      )
    end

end

app/helpers/whyt_plot_table_views_helper.rb
module WhytPlotTableViewsHelper
end

app/views/whyt_plot_table_views/_form.html.slim
= simple_form_for @whyt_plot_table_view, html: {class: 'form-inline' } do |f|

  - if flash[:errors].present?
    div
      ul class=["alert","alert-danger"]
        - flash[:errors].each do |msg|
          li = msg

  table.table.table-bordered.table-striped
    thead
      tr
        th
        th content
    tbody
      tr
        th name
        td = f.input :name, label: false
      tr
        th create_view_sql
        td = f.text_area :create_view_sql, size: "80x25", class: "form-control"
      tr
        th description
        td = f.text_area :description, size: "80x15", class: "form-control"
      tr
        th is view
        td = f.input :is_view, label: false
      tr
  - if @whyt_plot_table_view.id
    .actions.text-center = f.submit "確認・更新", class: "btn btn-default btn-lg"
  - else
    .actions.text-center = f.submit "新規作成", class: "btn btn-default btn-mg"

app/views/whyt_plot_table_views/edit.html.slim
div.pull-left
  h4 ビュー編集
  div[style="margin-bottom: 20px"]
    = link_to '一覧に戻る', whyt_plot_table_views_path
div.row

- if flash[:errors].present?
  div
    ul class=["alert","alert-danger"]
      - flash[:errors].each do |msg|
        li = msg

- if @whyt_plot_table_view.present?
  == render 'form'
- else
  div
    h4
      p データがありません

app/views/whyt_plot_table_views/index.html.slim
.row
  .col-lg-12
    div.pull-left
      h4 ビュー一覧
      div[style="margin-bottom: 20px"]
        = link_to 'API一覧', whyt_plot_apis_path
        = link_to 'インポート一覧', datafiles_path, :style => " margin-left: 10px"
        = link_to 'エクスポートエラ一覧', whytplot_export_errors_path, :style => " margin-left: 10px"

      div[style="margin-bottom: 20px"]
        - @sqlite_files.each do |key, url|
          ul.list-group
            - if key =~ /beta/
              li.list-group-item
                = link_to "テストデータ: #{key}", url, :style => "margin-left: 10px"
            - else
              li.list-group-item
                = link_to "本番データ: #{key}", url, :style => "margin-left: 10px"

    div.pull-right
      ul.list-group
        li.list-group-item
          = form_tag({ :controller => :whyt_plot_table_views, :action => :export }, { :method => :post }) do
            p= submit_tag "エクスポート", :class => "btn btn-success btn-large", :style => "margin-bottom: 5px; width: 100%"
            = check_box_tag 'is_production', true, false
            = label_tag 'is_production', '本番データを作成する'
        li.list-group-item.text-center
          = link_to '新規作成', new_whyt_plot_table_view_path,
          :class => "btn btn-primary btn-large", :style => "width: 100%"
.row
  .col-lg-12
    - if flash[:errors].present?
      div
        ul class=["alert","alert-danger"]
          - flash[:errors].each do |msg|
            li = msg

    - if flash[:notice].present?
      div
        ul class=["alert","alert-success"]
          li = flash[:notice]

.row
  .col-lg-12
    - if @whyt_plot_table_views.present?
      table.table.table-bordered.table-striped
        thead
          tr
            th id
            th name
            th create view sql
            th description
            th view
            th
        tbody
        - @whyt_plot_table_views.each do |whyt_plot_table_view|
          tr
            td = whyt_plot_table_view.id
            td = whyt_plot_table_view.name
            td = whyt_plot_table_view.create_view_sql
            th = whyt_plot_table_view.description
            th = whyt_plot_table_view.is_view
            th
              = link_to '表示', whyt_plot_table_view_path(whyt_plot_table_view), :class => "btn btn-success btn-sm"
              = link_to '編集', edit_whyt_plot_table_view_path(whyt_plot_table_view), :class => "btn btn-warning btn-sm"
              = link_to '削除', whyt_plot_table_view_path(whyt_plot_table_view),
                :method => :delete, :class => "btn btn-danger btn-sm",
                :data => {:confirm => "#{whyt_plot_table_view.name}テーブルを削除しますか？"}
    - else
      div
        h4
          p データがありません
.row
  .col-lg-12
    div.pull-left
      div[style="margin-bottom: 20px"]
        = link_to 'API一覧', whyt_plot_apis_path
        = link_to 'インポート一覧', datafiles_path, :style => " margin-left: 10px"
        = link_to 'エクスポートエラ一覧', whytplot_export_errors_path, :style => " margin-left: 10px"

app/views/whyt_plot_table_views/new.html.slim
div.pull-left
  h4 ビュー追加
  div[style="margin-bottom: 20px"]
    = link_to '一覧に戻る', whyt_plot_table_views_path
div.row

== render 'form'

app/views/whyt_plot_table_views/show.html.slim
div.pull-left
  strong API追加
div.pull-right
  = link_to 'テーブルビュー一覧', whyt_plot_table_views_path, :class => "btn btn-primary btn-large"

- if @whyt_plot_table_view.present?
  table.table.table-bordered.table-striped
    thead
      tr
        th id
        th name
        th create view sql
        th 作成済み
    tbody
      tr
        td = @whyt_plot_table_view.id
        td = @whyt_plot_table_view.name
        td = @whyt_plot_table_view.create_view_sql
        td = @whyt_plot_table_view.is_created
  .actions.text-center = link_to '編集', edit_whyt_plot_table_view_path(@whyt_plot_table_view), :class => "btn btn-success btn-large"
- else
  div
    h4
      p データがありません